# Generated by Django 5.2.6 on 2025-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creted',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='update',
        ),
        migrations.AddField(
            model_name='note',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
